[package]
name = "proxies"
version = "0.0.1"
edition = "2021"

[dependencies]
actix-files = "0.6.1"
actix-web = "4.1.0"
anyhow = "1.0.57"
chrono = { version = "0.4.19", features = ["serde"] }
config = "0.13.1"
dotenv = "0.15.0"
env_logger = "0.9.0"
log = "0.4.17"
once_cell = "1.12.0"
serde = "1.0.137"
serde_json = "1.0.81"
tera = "1.16.0"
