version: "3.7"

services:
  app:
    container_name: {{ app }}_app
    image: {{ app_image }}:{{ app_version }}
    command: main
    restart: always
    environment:
      - APP_NAME={{ app }}
      - DATABASE_URL=mongodb://postgres:{{ db_password }}@db/app
      - DOMAIN={{ domain }}
      - ACCESS_TOKEN={{ access_token }}
      - VIRTUAL_HOST={{ domain }}
      - LETSENCRYPT_HOST={{ domain }}
      - VIRTUAL_PORT=3000
    volumes:
      - app:/data
    networks:
      - nginx
      - default
    logging:
      driver: json-file
      options:
        max-size: 10m
{% if app_extra_ports %}
    ports:
{% for p in app_extra_ports %}
      - {{p}}:{{p}}
{% endfor %}
{% endif %}


  db:
    container_name: {{ app }}_db
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_PASSWORD={{ db_password }}
      - POSTGRES_DB=app
    volumes:
      - db:/data/db
    networks:
      - default
    logging:
      driver: json-file
      options:
        max-size: 10m

volumes:
  app:
  db:

networks:
  default:
  nginx:
    external: true
