- file: path=/apps/{{ app }} state=directory

- template: src=app.yml dest=/apps/{{ app }}/docker-compose.yml

- docker_login: registry={{ docker_registry }} username={{ docker_username }} password={{ docker_password }}

- docker_image: name={{ app_image }}:{{ app_version }} source=pull force_source=yes

- docker_compose: project_name={{ app }} project_src=/apps/{{ app }} state=present restarted=yes

- docker_prune: images=True
